controllerManager:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/henrywhitaker3/sre-operator
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 3
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
sreOperator:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
