apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  - deployments
  - pods
  - statefulsets
  verbs:
  - get
  - patch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - rollouts/finalizers
  verbs:
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - rollouts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts/finalizers
  verbs:
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - webhooks/finalizers
  verbs:
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - webhooks/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'