---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  - deployments
  - pods
  - statefulsets
  verbs:
  - get
  - patch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - rollouts/finalizers
  verbs:
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - rollouts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts/finalizers
  verbs:
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - webhooks/finalizers
  verbs:
  - update
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - webhooks/status
  verbs:
  - get
  - patch
  - update
