---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - configuration.sre.henrywhitaker.com
  resources:
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configuration.sre.henrywhitaker.com
  resources:
  - webhooks/finalizers
  verbs:
  - update
- apiGroups:
  - configuration.sre.henrywhitaker.com
  resources:
  - webhooks/status
  verbs:
  - get
  - patch
  - update
