# permissions for end users to view scripts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: script-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sre-operator
    app.kubernetes.io/part-of: sre-operator
    app.kubernetes.io/managed-by: kustomize
  name: script-viewer-role
rules:
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sre.henrywhitaker.com
  resources:
  - scripts/status
  verbs:
  - get
