apiVersion: sre.henrywhitaker.com/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: rollout
    app.kubernetes.io/instance: rollout-sample
    app.kubernetes.io/part-of: sre-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sre-operator
  name: rollout-sample
spec:
  hook: bongos
  target:
    kind: deployment
    namespace: default
    name: debug
  action: restart
